- hosts: allserver
  vars:
    - image: randyaji/apache-custom
  tasks:
    - name: Install Python-docker
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-docker
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Python-docker
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - epel-release
        - python3
        - python3-docker
      when: ansible_facts['os_family'] == "RedHat"
   
    - name: pull image docker
      docker_image:
        name: "{{ image }}"
        state: present
        force: yes

    - name: create container
      docker_container:
        name: docker-ansible
        image: "{{ image }}"
        state: started
        published_ports:
          - 10000:80
        recreate: yes
